export const SET_MENU = 'SET_MENU'
export const SET_All_MENU = 'SET_All_MENU'

export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST'
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS'
export const FETCH_MENU_ERROR = 'FETCH_MENU_ERROR'

export const FETCH_ALL_MENU_REQUEST = 'FETCH_ALL_MENU_REQUEST'
export const FETCH_ALL_MENU_SUCCESS = 'FETCH_ALL_MENU_SUCCESS'
export const FETCH_ALL_MENU_ERROR = 'FETCH_ALL_MENU_ERROR'
