export const CHANGE_NAME = 'CHANGE_NAME'

export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST'
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS'
export const FETCH_POKEMON_ERROR = 'FETCH_POKEMON_ERROR'
